[*] Running ...
[*] Dataset loaded: E:\Coding\pythonProject\llm4contract\problems\dataset\train_01.pkl with 5 instances.
→ Best principal utility: 4.03773573646638
→ Best action index:    98
→ Best contract w:       [0.94877393 0.         0.         4.06570984 4.98148626]
Traceback (most recent call last):
  File "E:\Coding\pythonProject\llm4contract\problems\eval.py", line 150, in <module>
    obj = evaluate_llm((_p, _c, _v, _contract_logs))
  File "E:\Coding\pythonProject\llm4contract\problems\eval.py", line 101, in evaluate_llm
    inferred_agent_setting = llm_agent_solver(v, content)
  File "E:\Coding\pythonProject\llm4contract\problems\gpt.py", line 70, in agent_solver
    return p
  File "E:\Coding\pythonProject\llm4contract\problems\gpt.py", line 59, in solve_p_given_w_u
    A_eq[0, :m] = 1
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\scipy\optimize\_nnls.py", line 87, in nnls
    raise ValueError(
ValueError: Incompatible dimensions. The first dimension of A is 5, while the shape of b is (2,)
