[*] Running ...
[*] Dataset loaded: E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\dataset\train_01.pkl with 3 instances.
â†’ Best principal utility: 0.0006193891649213826
Traceback (most recent call last):
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\eval.py", line 162, in <module>
    obj, _ = evaluate_llm((_p, _c, _v, _contract_logs))
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\eval.py", line 101, in evaluate_llm
    inferred_agent_setting = llm_agent_solver(v, content)
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\gpt.py", line 26, in agent_solver_v2
    
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\gpt.py", line 18, in mini_lp_p
    candidate_ps = []
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\scipy\optimize\_linprog.py", line 649, in linprog
    lp, solver_options = _parse_linprog(lp, options, meth)
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\scipy\optimize\_linprog_util.py", line 1026, in _parse_linprog
    lp = _clean_inputs(lp._replace(A_ub=A_ub, A_eq=A_eq))
  File "D:\Software\anaconda3\envs\llm4contract\lib\site-packages\scipy\optimize\_linprog_util.py", line 320, in _clean_inputs
    raise ValueError(
ValueError: Invalid input for linprog: A_ub must have exactly two dimensions, and the number of columns in A_ub must be equal to the size of c
