Traceback (most recent call last):
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\eval.py", line 13, in <module>
    from problems.online_contract_edgeAI import gpt
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\gpt.py", line 72, in <module>
    agent_setting = agent_solver_v2(v, content)
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\gpt.py", line 28, in agent_solver_v2
    raise ValueError("No valid accepted logs to infer agent strategies.")
ValueError: No valid accepted logs to infer agent strategies.
